service:
  externalPort: 3000
  internalPort: 3000
image:
  secrets:
  - name: skdigital-bonet-registry
livenessProbe.initialDelaySeconds: 20
readinessProbe.initialDelaySeconds: 20 
application.migrateCommand: ["bundle", "exec", "rails", "db:migrate"]
resources:
  requests:
    cpu: 20m
    memory: 180Mi
  limits:
    memory: 400Mi
workers:
  clock:
    replicaCount: "1"
    command: ["bundle", "exec", "clockwork", "config/clock.rb"]
    terminationGracePeriodSeconds:  60
    livenessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 10
      probeType: "exec"
      command:
        - "pgrep"
        - "bundle"
    readinessProbe:
      probeType: "exec"
      command:
        - "pgrep"
        - "bundle"
    resources:
      requests:
        cpu: 5m
        memory: 100Mi
      limits:
        memory: 150Mi
  worker:
    replicaCount: "1"
    command: ["bundle", "exec", "que", "-w1", "./config/environment.rb"]
    terminationGracePeriodSeconds:  60
    livenessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 10
      probeType: "exec"
      command:
        - "pgrep"
        - "bundle"
    readinessProbe:
      probeType: "exec"
      command:
        - "pgrep"
        - "bundle"
    resources:
      requests:
        cpu: 10m
        memory: 120Mi
      limits:
        memory: 200Mi
