default: &default
  host: <%= ENV.fetch('APP_HOST', 'localhost') %>
  port: <%= ENV.fetch('APP_PORT', '') %>
  protocol: <%= ENV.fetch('APP_PROTOCOL', 'http') %>

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
