servers:
  web:
    hosts:
      - dev.slovensko.digital
    options:
      memory: 400m

  worker:
    hosts:
      - dev.slovensko.digital
    options:
      memory: 500m

  clock:
    hosts:
      - dev.slovensko.digital
    options:
      memory: 150m

env:
  clear:
    RAILS_ENV: production
    RAILS_LOG_LEVEL: info
    RAILS_LOG_TO_STDOUT: "true"
    RAILS_SERVE_STATIC_FILES: "true"
    APP_HOST: redflags.staging.slovensko.digital
    ROLLBAR_ENV: staging
    GOOGLE_SHEET_ID: 1QUphB9a0sV7Db3Vln9idYeiar3nY_4eFa2GTyLbVQ0w
    GOOGLE_SHEET_EXPORT_ID: 17D8meP_tDwIYn2ZENM_s_DsH-wwdnFWVTI-v9q9DnDw

proxy:
  host: redflags.staging.slovensko.digital

ssh:
  user: kamal
