# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

RatingType.find_or_create_by!(name: 'Reforma VS')
RatingType.find_or_create_by!(name: 'Merateľné ciele (KPI)')
RatingType.find_or_create_by!(name: 'Postup dosiahnutia cieľov')
RatingType.find_or_create_by!(name: 'Súlad s KRIS')
RatingType.find_or_create_by!(name: 'Biznis prínos')
RatingType.find_or_create_by!(name: 'Príspevok v informatizácii')
RatingType.find_or_create_by!(name: 'Štúdia uskutočniteľnosti')
RatingType.find_or_create_by!(name: 'Alternatívy')
RatingType.find_or_create_by!(name: 'Kalkulácia efektívnosti')
RatingType.find_or_create_by!(name: 'Participácia na príprave projektu')
RatingType.find_or_create_by!(name: 'Stratégia obstarávania')
RatingType.find_or_create_by!(name: 'Prípravné trhové konzultácie')
RatingType.find_or_create_by!(name: 'Druh postupu')
RatingType.find_or_create_by!(name: 'Predmet zákazky')
RatingType.find_or_create_by!(name: 'Rozdelenie na časti')
RatingType.find_or_create_by!(name: 'Podmienky účasti')
RatingType.find_or_create_by!(name: 'Kritériá hodnotenia')
RatingType.find_or_create_by!(name: 'Vendor Lock-in a Autorské práva')
RatingType.find_or_create_by!(name: 'Lehoty')
RatingType.find_or_create_by!(name: 'Obchodné podmienky')
RatingType.find_or_create_by!(name: 'Vyhodnotenie obstarávania')
RatingType.find_or_create_by!(name: 'Hospodárska súťaž')
RatingType.find_or_create_by!(name: 'Cena')
RatingType.find_or_create_by!(name: 'Subdodávatelia')

ProjectStage.find_or_create_by!(name: 'Príprava projektu').update!(position: 1)
ProjectStage.find_or_create_by!(name: 'Obstarávanie').update!(position: 2)
ProjectStage.find_or_create_by!(name: 'Realizácia projektu').update!(position: 3)
ProjectStage.find_or_create_by!(name: 'Testovacia prevádzka').update!(position: 4)
ProjectStage.find_or_create_by!(name: 'Prevádzka').update!(position: 5)
ProjectStage.find_or_create_by!(name: 'Zastavený projekt').update!(position: 998)
ProjectStage.find_or_create_by!(name: 'Zrušený projekt').update!(position: 999)
